epochs: 100
val_epoch_freq: 1
transfer_epochs: 50
batch_size: 16
model_type: QTSeg
encoder_model: FPNEncoder
decoder_model: MaskDecoder
metric : Binary
loss_type:
  - CrossEntropyLoss
  - BinaryDiceLoss
optimizer: adamw
scheduler: StepLR
learning_rate: 0.001
dataloader: BKAI
data_root: working/dataset/BKAI
valid_type: test
