name: myenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.11
  - cudatoolkit=11.1
  - pytorch=1.8.0
  - torchvision=0.9.0
  - torchaudio=0.8.0
  - absl-py=0.13.0
  - cachetools=4.2.2
  - charset-normalizer=2.0.4
  - cycler=0.10.0
  - ffmpeg=4.3
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - grpcio=1.40.0
  - idna=3.2
  - imageio=2.9.0
  - imgaug=0.4.0
  - joblib=1.0.1
  - kiwisolver=1.3.2
  - markdown=3.3.4
  - matplotlib=3.4.3
  - networkx=2.6.2
  - numpy=1.20.3
  - oauthlib=3.1.1
  - olefile=0.46
  - opencv=4.5.3
  - pillow=8.3.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pyparsing=2.4.7
  - python-dateutil=2.8.2
  - pytz=2021.1
  - pywavelets=1.1.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-image=0.18.3
  - scikit-learn=0.24.2
  - shapely=1.7.1
  - six=1.16.0
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.0
  - threadpoolctl=2.2.0
  - tifffile=2021.8.30
  - typing_extensions=3.10.0.0
  - urllib3=1.26.6
  - werkzeug=2.0.1
  - pip  # pip 사용을 위해 추가
  - pip:
      # conda에서 설치할 수 없는 패키지를 pip로 설치
      - imgaug==0.4.0
